# Clés disponibles dans SonarCloud > ton projet > Information (icone ⓘ)
sonar.projectKey=PaulOwO_CeziZen-DevopsTp
sonar.organization=paulowo

# Dossiers à analyser
sonar.sources=.

# Dossiers à ignorer (générés, dépendances)
sonar.exclusions=node_modules/**,dist/**,.nuxt/**,.output/**,coverage/**,.git/**

# Encodage
sonar.sourceEncoding=UTF-8
